"""add exercise media urls

Revision ID: add_exercise_media_urls
Revises: 
Create Date: 2026-04-26 22:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_exercise_media_urls'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('exercise_image_url', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('exercise_video_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'exercise_video_url')
    op.drop_column('tasks', 'exercise_image_url')
    # ### end Alembic commands ###
